// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	label "github.com/bazelbuild/bazel-gazelle/label"
	mock "github.com/stretchr/testify/mock"

	parse "github.com/stackb/scala-gazelle/build/stack/gazelle/scala/parse"
)

// Compiler is an autogenerated mock type for the Compiler type
type Compiler struct {
	mock.Mock
}

// CompileScalaFiles provides a mock function with given fields: from, dir, srcs
func (_m *Compiler) CompileScalaFiles(from label.Label, dir string, srcs ...string) ([]*parse.File, error) {
	_va := make([]interface{}, len(srcs))
	for _i := range srcs {
		_va[_i] = srcs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, from, dir)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*parse.File
	if rf, ok := ret.Get(0).(func(label.Label, string, ...string) []*parse.File); ok {
		r0 = rf(from, dir, srcs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*parse.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(label.Label, string, ...string) error); ok {
		r1 = rf(from, dir, srcs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCompiler interface {
	mock.TestingT
	Cleanup(func())
}

// NewCompiler creates a new instance of Compiler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCompiler(t mockConstructorTestingTNewCompiler) *Compiler {
	mock := &Compiler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
