// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: scala/meta/semanticdb/semanticidx.proto

package semanticdb

import (
	_ "github.com/stackb/scala-gazelle/scalapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Indexes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indexes []*Index `protobuf:"bytes,1,rep,name=indexes,proto3" json:"indexes,omitempty"`
}

func (x *Indexes) Reset() {
	*x = Indexes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Indexes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indexes) ProtoMessage() {}

func (x *Indexes) ProtoReflect() protoreflect.Message {
	mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indexes.ProtoReflect.Descriptor instead.
func (*Indexes) Descriptor() ([]byte, []int) {
	return file_scala_meta_semanticdb_semanticidx_proto_rawDescGZIP(), []int{0}
}

func (x *Indexes) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type Index struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries map[string]*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Index) Reset() {
	*x = Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_scala_meta_semanticdb_semanticidx_proto_rawDescGZIP(), []int{1}
}

func (x *Index) GetEntries() map[string]*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to SealedValue:
	//	*Entry_PackageEntry
	//	*Entry_ToplevelEntry
	SealedValue isEntry_SealedValue `protobuf_oneof:"sealed_value"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_scala_meta_semanticdb_semanticidx_proto_rawDescGZIP(), []int{2}
}

func (m *Entry) GetSealedValue() isEntry_SealedValue {
	if m != nil {
		return m.SealedValue
	}
	return nil
}

func (x *Entry) GetPackageEntry() *PackageEntry {
	if x, ok := x.GetSealedValue().(*Entry_PackageEntry); ok {
		return x.PackageEntry
	}
	return nil
}

func (x *Entry) GetToplevelEntry() *ToplevelEntry {
	if x, ok := x.GetSealedValue().(*Entry_ToplevelEntry); ok {
		return x.ToplevelEntry
	}
	return nil
}

type isEntry_SealedValue interface {
	isEntry_SealedValue()
}

type Entry_PackageEntry struct {
	PackageEntry *PackageEntry `protobuf:"bytes,1,opt,name=packageEntry,proto3,oneof"`
}

type Entry_ToplevelEntry struct {
	ToplevelEntry *ToplevelEntry `protobuf:"bytes,2,opt,name=toplevelEntry,proto3,oneof"`
}

func (*Entry_PackageEntry) isEntry_SealedValue() {}

func (*Entry_ToplevelEntry) isEntry_SealedValue() {}

type PackageEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PackageEntry) Reset() {
	*x = PackageEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageEntry) ProtoMessage() {}

func (x *PackageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageEntry.ProtoReflect.Descriptor instead.
func (*PackageEntry) Descriptor() ([]byte, []int) {
	return file_scala_meta_semanticdb_semanticidx_proto_rawDescGZIP(), []int{3}
}

type ToplevelEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *ToplevelEntry) Reset() {
	*x = ToplevelEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToplevelEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToplevelEntry) ProtoMessage() {}

func (x *ToplevelEntry) ProtoReflect() protoreflect.Message {
	mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToplevelEntry.ProtoReflect.Descriptor instead.
func (*ToplevelEntry) Descriptor() ([]byte, []int) {
	return file_scala_meta_semanticdb_semanticidx_proto_rawDescGZIP(), []int{4}
}

func (x *ToplevelEntry) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type InfoMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries map[string]string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *InfoMap) Reset() {
	*x = InfoMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoMap) ProtoMessage() {}

func (x *InfoMap) ProtoReflect() protoreflect.Message {
	mi := &file_scala_meta_semanticdb_semanticidx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoMap.ProtoReflect.Descriptor instead.
func (*InfoMap) Descriptor() ([]byte, []int) {
	return file_scala_meta_semanticdb_semanticidx_proto_rawDescGZIP(), []int{5}
}

func (x *InfoMap) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_scala_meta_semanticdb_semanticidx_proto protoreflect.FileDescriptor

var file_scala_meta_semanticdb_semanticidx_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x73, 0x65, 0x6d,
	0x61, 0x6e, 0x74, 0x69, 0x63, 0x64, 0x62, 0x2f, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63,
	0x69, 0x64, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x63, 0x61, 0x6c, 0x61,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x64, 0x62,
	0x1a, 0x15, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x70, 0x62, 0x2f, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x70,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x07, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x65, 0x73, 0x12, 0x36, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x64, 0x62, 0x2e, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x05, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x43, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x64, 0x62, 0x2e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x58, 0x0a, 0x0c, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x63, 0x61,
	0x6c, 0x61, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63,
	0x64, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0xb0, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x49, 0x0a,
	0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x64, 0x62, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x4c, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x73, 0x65, 0x6d,
	0x61, 0x6e, 0x74, 0x69, 0x63, 0x64, 0x62, 0x2e, 0x54, 0x6f, 0x70, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x00, 0x52, 0x0d, 0x74, 0x6f, 0x70, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x0e, 0x0a, 0x0c, 0x73, 0x65, 0x61, 0x6c, 0x65, 0x64,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x21, 0x0a, 0x0d, 0x54, 0x6f, 0x70, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x8c, 0x01, 0x0a, 0x07, 0x49, 0x6e,
	0x66, 0x6f, 0x4d, 0x61, 0x70, 0x12, 0x45, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x64, 0x62, 0x2e, 0x49,
	0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x70, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x0c,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x47, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x62, 0x2f, 0x73, 0x63,
	0x61, 0x6c, 0x61, 0x2d, 0x67, 0x61, 0x7a, 0x65, 0x6c, 0x6c, 0x65, 0x2f, 0x73, 0x63, 0x61, 0x6c,
	0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x64,
	0x62, 0x3b, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x64, 0x62, 0xe2, 0x3f, 0x02, 0x48,
	0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scala_meta_semanticdb_semanticidx_proto_rawDescOnce sync.Once
	file_scala_meta_semanticdb_semanticidx_proto_rawDescData = file_scala_meta_semanticdb_semanticidx_proto_rawDesc
)

func file_scala_meta_semanticdb_semanticidx_proto_rawDescGZIP() []byte {
	file_scala_meta_semanticdb_semanticidx_proto_rawDescOnce.Do(func() {
		file_scala_meta_semanticdb_semanticidx_proto_rawDescData = protoimpl.X.CompressGZIP(file_scala_meta_semanticdb_semanticidx_proto_rawDescData)
	})
	return file_scala_meta_semanticdb_semanticidx_proto_rawDescData
}

var file_scala_meta_semanticdb_semanticidx_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_scala_meta_semanticdb_semanticidx_proto_goTypes = []interface{}{
	(*Indexes)(nil),       // 0: scala.meta.semanticdb.Indexes
	(*Index)(nil),         // 1: scala.meta.semanticdb.Index
	(*Entry)(nil),         // 2: scala.meta.semanticdb.Entry
	(*PackageEntry)(nil),  // 3: scala.meta.semanticdb.PackageEntry
	(*ToplevelEntry)(nil), // 4: scala.meta.semanticdb.ToplevelEntry
	(*InfoMap)(nil),       // 5: scala.meta.semanticdb.InfoMap
	nil,                   // 6: scala.meta.semanticdb.Index.EntriesEntry
	nil,                   // 7: scala.meta.semanticdb.InfoMap.EntriesEntry
}
var file_scala_meta_semanticdb_semanticidx_proto_depIdxs = []int32{
	1, // 0: scala.meta.semanticdb.Indexes.indexes:type_name -> scala.meta.semanticdb.Index
	6, // 1: scala.meta.semanticdb.Index.entries:type_name -> scala.meta.semanticdb.Index.EntriesEntry
	3, // 2: scala.meta.semanticdb.Entry.packageEntry:type_name -> scala.meta.semanticdb.PackageEntry
	4, // 3: scala.meta.semanticdb.Entry.toplevelEntry:type_name -> scala.meta.semanticdb.ToplevelEntry
	7, // 4: scala.meta.semanticdb.InfoMap.entries:type_name -> scala.meta.semanticdb.InfoMap.EntriesEntry
	2, // 5: scala.meta.semanticdb.Index.EntriesEntry.value:type_name -> scala.meta.semanticdb.Entry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_scala_meta_semanticdb_semanticidx_proto_init() }
func file_scala_meta_semanticdb_semanticidx_proto_init() {
	if File_scala_meta_semanticdb_semanticidx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scala_meta_semanticdb_semanticidx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Indexes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scala_meta_semanticdb_semanticidx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scala_meta_semanticdb_semanticidx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scala_meta_semanticdb_semanticidx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scala_meta_semanticdb_semanticidx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToplevelEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scala_meta_semanticdb_semanticidx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_scala_meta_semanticdb_semanticidx_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Entry_PackageEntry)(nil),
		(*Entry_ToplevelEntry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scala_meta_semanticdb_semanticidx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scala_meta_semanticdb_semanticidx_proto_goTypes,
		DependencyIndexes: file_scala_meta_semanticdb_semanticidx_proto_depIdxs,
		MessageInfos:      file_scala_meta_semanticdb_semanticidx_proto_msgTypes,
	}.Build()
	File_scala_meta_semanticdb_semanticidx_proto = out.File
	file_scala_meta_semanticdb_semanticidx_proto_rawDesc = nil
	file_scala_meta_semanticdb_semanticidx_proto_goTypes = nil
	file_scala_meta_semanticdb_semanticidx_proto_depIdxs = nil
}
