// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	config "github.com/bazelbuild/bazel-gazelle/config"
	label "github.com/bazelbuild/bazel-gazelle/label"

	mock "github.com/stretchr/testify/mock"

	resolve "github.com/bazelbuild/bazel-gazelle/resolve"

	resolver "github.com/stackb/scala-gazelle/pkg/resolver"
)

// KnownImportResolver is an autogenerated mock type for the KnownImportResolver type
type KnownImportResolver struct {
	mock.Mock
}

// ResolveKnownImport provides a mock function with given fields: c, ix, from, lang, sym
func (_m *KnownImportResolver) ResolveKnownImport(c *config.Config, ix *resolve.RuleIndex, from label.Label, lang string, sym string) (*resolver.KnownImport, error) {
	ret := _m.Called(c, ix, from, lang, sym)

	var r0 *resolver.KnownImport
	if rf, ok := ret.Get(0).(func(*config.Config, *resolve.RuleIndex, label.Label, string, string) *resolver.KnownImport); ok {
		r0 = rf(c, ix, from, lang, sym)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resolver.KnownImport)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*config.Config, *resolve.RuleIndex, label.Label, string, string) error); ok {
		r1 = rf(c, ix, from, lang, sym)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewKnownImportResolver interface {
	mock.TestingT
	Cleanup(func())
}

// NewKnownImportResolver creates a new instance of KnownImportResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKnownImportResolver(t mockConstructorTestingTNewKnownImportResolver) *KnownImportResolver {
	mock := &KnownImportResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
