// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	flag "flag"

	config "github.com/bazelbuild/bazel-gazelle/config"

	label "github.com/bazelbuild/bazel-gazelle/label"

	mock "github.com/stretchr/testify/mock"

	resolver "github.com/stackb/scala-gazelle/pkg/resolver"

	rule "github.com/bazelbuild/bazel-gazelle/rule"
)

// SymbolProvider is an autogenerated mock type for the SymbolProvider type
type SymbolProvider struct {
	mock.Mock
}

// CanProvide provides a mock function with given fields: dep, knownRule
func (_m *SymbolProvider) CanProvide(dep label.Label, knownRule func(label.Label) (*rule.Rule, bool)) bool {
	ret := _m.Called(dep, knownRule)

	var r0 bool
	if rf, ok := ret.Get(0).(func(label.Label, func(label.Label) (*rule.Rule, bool)) bool); ok {
		r0 = rf(dep, knownRule)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CheckFlags provides a mock function with given fields: fs, c, registry
func (_m *SymbolProvider) CheckFlags(fs *flag.FlagSet, c *config.Config, registry resolver.Scope) error {
	ret := _m.Called(fs, c, registry)

	var r0 error
	if rf, ok := ret.Get(0).(func(*flag.FlagSet, *config.Config, resolver.Scope) error); ok {
		r0 = rf(fs, c, registry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *SymbolProvider) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OnResolve provides a mock function with given fields:
func (_m *SymbolProvider) OnResolve() {
	_m.Called()
}

// RegisterFlags provides a mock function with given fields: fs, cmd, c
func (_m *SymbolProvider) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	_m.Called(fs, cmd, c)
}

type mockConstructorTestingTNewSymbolProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewSymbolProvider creates a new instance of SymbolProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSymbolProvider(t mockConstructorTestingTNewSymbolProvider) *SymbolProvider {
	mock := &SymbolProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
