// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	config "github.com/bazelbuild/bazel-gazelle/config"
	label "github.com/bazelbuild/bazel-gazelle/label"

	mock "github.com/stretchr/testify/mock"

	resolve "github.com/bazelbuild/bazel-gazelle/resolve"

	resolver "github.com/stackb/scala-gazelle/pkg/resolver"

	rule "github.com/bazelbuild/bazel-gazelle/rule"
)

// Universe is an autogenerated mock type for the Universe type
type Universe struct {
	mock.Mock
}

// AddSymbolProvider provides a mock function with given fields: provider
func (_m *Universe) AddSymbolProvider(provider resolver.SymbolProvider) error {
	ret := _m.Called(provider)

	var r0 error
	if rf, ok := ret.Get(0).(func(resolver.SymbolProvider) error); ok {
		r0 = rf(provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetKnownRule provides a mock function with given fields: from
func (_m *Universe) GetKnownRule(from label.Label) (*rule.Rule, bool) {
	ret := _m.Called(from)

	var r0 *rule.Rule
	if rf, ok := ret.Get(0).(func(label.Label) *rule.Rule); ok {
		r0 = rf(from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rule.Rule)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(label.Label) bool); ok {
		r1 = rf(from)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetSymbol provides a mock function with given fields: imp
func (_m *Universe) GetSymbol(imp string) (*resolver.Symbol, bool) {
	ret := _m.Called(imp)

	var r0 *resolver.Symbol
	if rf, ok := ret.Get(0).(func(string) *resolver.Symbol); ok {
		r0 = rf(imp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resolver.Symbol)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(imp)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetSymbols provides a mock function with given fields: prefix
func (_m *Universe) GetSymbols(prefix string) []*resolver.Symbol {
	ret := _m.Called(prefix)

	var r0 []*resolver.Symbol
	if rf, ok := ret.Get(0).(func(string) []*resolver.Symbol); ok {
		r0 = rf(prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*resolver.Symbol)
		}
	}

	return r0
}

// PutKnownRule provides a mock function with given fields: from, r
func (_m *Universe) PutKnownRule(from label.Label, r *rule.Rule) error {
	ret := _m.Called(from, r)

	var r0 error
	if rf, ok := ret.Get(0).(func(label.Label, *rule.Rule) error); ok {
		r0 = rf(from, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutSymbol provides a mock function with given fields: known
func (_m *Universe) PutSymbol(known *resolver.Symbol) error {
	ret := _m.Called(known)

	var r0 error
	if rf, ok := ret.Get(0).(func(*resolver.Symbol) error); ok {
		r0 = rf(known)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResolveSymbol provides a mock function with given fields: c, ix, from, lang, sym
func (_m *Universe) ResolveSymbol(c *config.Config, ix *resolve.RuleIndex, from label.Label, lang string, sym string) (*resolver.Symbol, error) {
	ret := _m.Called(c, ix, from, lang, sym)

	var r0 *resolver.Symbol
	if rf, ok := ret.Get(0).(func(*config.Config, *resolve.RuleIndex, label.Label, string, string) *resolver.Symbol); ok {
		r0 = rf(c, ix, from, lang, sym)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resolver.Symbol)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*config.Config, *resolve.RuleIndex, label.Label, string, string) error); ok {
		r1 = rf(c, ix, from, lang, sym)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SymbolProviders provides a mock function with given fields:
func (_m *Universe) SymbolProviders() []resolver.SymbolProvider {
	ret := _m.Called()

	var r0 []resolver.SymbolProvider
	if rf, ok := ret.Get(0).(func() []resolver.SymbolProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resolver.SymbolProvider)
		}
	}

	return r0
}

type mockConstructorTestingTNewUniverse interface {
	mock.TestingT
	Cleanup(func())
}

// NewUniverse creates a new instance of Universe. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUniverse(t mockConstructorTestingTNewUniverse) *Universe {
	mock := &Universe{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
