// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: scalapb/scalapb.proto

package scalapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalaPbOptions_OptionsScope int32

const (
	ScalaPbOptions_FILE    ScalaPbOptions_OptionsScope = 0
	ScalaPbOptions_PACKAGE ScalaPbOptions_OptionsScope = 1
)

// Enum value maps for ScalaPbOptions_OptionsScope.
var (
	ScalaPbOptions_OptionsScope_name = map[int32]string{
		0: "FILE",
		1: "PACKAGE",
	}
	ScalaPbOptions_OptionsScope_value = map[string]int32{
		"FILE":    0,
		"PACKAGE": 1,
	}
)

func (x ScalaPbOptions_OptionsScope) Enum() *ScalaPbOptions_OptionsScope {
	p := new(ScalaPbOptions_OptionsScope)
	*p = x
	return p
}

func (x ScalaPbOptions_OptionsScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalaPbOptions_OptionsScope) Descriptor() protoreflect.EnumDescriptor {
	return file_scalapb_scalapb_proto_enumTypes[0].Descriptor()
}

func (ScalaPbOptions_OptionsScope) Type() protoreflect.EnumType {
	return &file_scalapb_scalapb_proto_enumTypes[0]
}

func (x ScalaPbOptions_OptionsScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ScalaPbOptions_OptionsScope) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ScalaPbOptions_OptionsScope(num)
	return nil
}

// Deprecated: Use ScalaPbOptions_OptionsScope.Descriptor instead.
func (ScalaPbOptions_OptionsScope) EnumDescriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{0, 0}
}

type ScalaPbOptions_EnumValueNaming int32

const (
	ScalaPbOptions_AS_IN_PROTO ScalaPbOptions_EnumValueNaming = 0
	ScalaPbOptions_CAMEL_CASE  ScalaPbOptions_EnumValueNaming = 1
)

// Enum value maps for ScalaPbOptions_EnumValueNaming.
var (
	ScalaPbOptions_EnumValueNaming_name = map[int32]string{
		0: "AS_IN_PROTO",
		1: "CAMEL_CASE",
	}
	ScalaPbOptions_EnumValueNaming_value = map[string]int32{
		"AS_IN_PROTO": 0,
		"CAMEL_CASE":  1,
	}
)

func (x ScalaPbOptions_EnumValueNaming) Enum() *ScalaPbOptions_EnumValueNaming {
	p := new(ScalaPbOptions_EnumValueNaming)
	*p = x
	return p
}

func (x ScalaPbOptions_EnumValueNaming) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalaPbOptions_EnumValueNaming) Descriptor() protoreflect.EnumDescriptor {
	return file_scalapb_scalapb_proto_enumTypes[1].Descriptor()
}

func (ScalaPbOptions_EnumValueNaming) Type() protoreflect.EnumType {
	return &file_scalapb_scalapb_proto_enumTypes[1]
}

func (x ScalaPbOptions_EnumValueNaming) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ScalaPbOptions_EnumValueNaming) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ScalaPbOptions_EnumValueNaming(num)
	return nil
}

// Deprecated: Use ScalaPbOptions_EnumValueNaming.Descriptor instead.
func (ScalaPbOptions_EnumValueNaming) EnumDescriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{0, 1}
}

type ScalaPbOptions struct {
	state                        protoimpl.MessageState              `protogen:"open.v1"`
	PackageName                  *string                             `protobuf:"bytes,1,opt,name=package_name,json=packageName" json:"package_name,omitempty"`
	FlatPackage                  *bool                               `protobuf:"varint,2,opt,name=flat_package,json=flatPackage" json:"flat_package,omitempty"`
	Import                       []string                            `protobuf:"bytes,3,rep,name=import" json:"import,omitempty"`
	Preamble                     []string                            `protobuf:"bytes,4,rep,name=preamble" json:"preamble,omitempty"`
	SingleFile                   *bool                               `protobuf:"varint,5,opt,name=single_file,json=singleFile" json:"single_file,omitempty"`
	NoPrimitiveWrappers          *bool                               `protobuf:"varint,7,opt,name=no_primitive_wrappers,json=noPrimitiveWrappers" json:"no_primitive_wrappers,omitempty"`
	PrimitiveWrappers            *bool                               `protobuf:"varint,6,opt,name=primitive_wrappers,json=primitiveWrappers" json:"primitive_wrappers,omitempty"`
	CollectionType               *string                             `protobuf:"bytes,8,opt,name=collection_type,json=collectionType" json:"collection_type,omitempty"`
	PreserveUnknownFields        *bool                               `protobuf:"varint,9,opt,name=preserve_unknown_fields,json=preserveUnknownFields,def=1" json:"preserve_unknown_fields,omitempty"`
	ObjectName                   *string                             `protobuf:"bytes,10,opt,name=object_name,json=objectName" json:"object_name,omitempty"`
	Scope                        *ScalaPbOptions_OptionsScope        `protobuf:"varint,11,opt,name=scope,enum=scalapb.ScalaPbOptions_OptionsScope" json:"scope,omitempty"`
	Lenses                       *bool                               `protobuf:"varint,12,opt,name=lenses,def=1" json:"lenses,omitempty"`
	RetainSourceCodeInfo         *bool                               `protobuf:"varint,13,opt,name=retain_source_code_info,json=retainSourceCodeInfo" json:"retain_source_code_info,omitempty"`
	MapType                      *string                             `protobuf:"bytes,14,opt,name=map_type,json=mapType" json:"map_type,omitempty"`
	NoDefaultValuesInConstructor *bool                               `protobuf:"varint,15,opt,name=no_default_values_in_constructor,json=noDefaultValuesInConstructor" json:"no_default_values_in_constructor,omitempty"`
	EnumValueNaming              *ScalaPbOptions_EnumValueNaming     `protobuf:"varint,16,opt,name=enum_value_naming,json=enumValueNaming,enum=scalapb.ScalaPbOptions_EnumValueNaming" json:"enum_value_naming,omitempty"`
	EnumStripPrefix              *bool                               `protobuf:"varint,17,opt,name=enum_strip_prefix,json=enumStripPrefix,def=0" json:"enum_strip_prefix,omitempty"`
	AuxMessageOptions            []*ScalaPbOptions_AuxMessageOptions `protobuf:"bytes,18,rep,name=aux_message_options,json=auxMessageOptions" json:"aux_message_options,omitempty"`
	AuxFieldOptions              []*ScalaPbOptions_AuxFieldOptions   `protobuf:"bytes,19,rep,name=aux_field_options,json=auxFieldOptions" json:"aux_field_options,omitempty"`
	AuxEnumOptions               []*ScalaPbOptions_AuxEnumOptions    `protobuf:"bytes,20,rep,name=aux_enum_options,json=auxEnumOptions" json:"aux_enum_options,omitempty"`
	BytesType                    *string                             `protobuf:"bytes,21,opt,name=bytes_type,json=bytesType" json:"bytes_type,omitempty"`
	TestOnlyNoJavaConversions    *bool                               `protobuf:"varint,100001,opt,name=test_only_no_java_conversions,json=testOnlyNoJavaConversions" json:"test_only_no_java_conversions,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

// Default values for ScalaPbOptions fields.
const (
	Default_ScalaPbOptions_PreserveUnknownFields = bool(true)
	Default_ScalaPbOptions_Lenses                = bool(true)
	Default_ScalaPbOptions_EnumStripPrefix       = bool(false)
)

func (x *ScalaPbOptions) Reset() {
	*x = ScalaPbOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalaPbOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalaPbOptions) ProtoMessage() {}

func (x *ScalaPbOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalaPbOptions.ProtoReflect.Descriptor instead.
func (*ScalaPbOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{0}
}

func (x *ScalaPbOptions) GetPackageName() string {
	if x != nil && x.PackageName != nil {
		return *x.PackageName
	}
	return ""
}

func (x *ScalaPbOptions) GetFlatPackage() bool {
	if x != nil && x.FlatPackage != nil {
		return *x.FlatPackage
	}
	return false
}

func (x *ScalaPbOptions) GetImport() []string {
	if x != nil {
		return x.Import
	}
	return nil
}

func (x *ScalaPbOptions) GetPreamble() []string {
	if x != nil {
		return x.Preamble
	}
	return nil
}

func (x *ScalaPbOptions) GetSingleFile() bool {
	if x != nil && x.SingleFile != nil {
		return *x.SingleFile
	}
	return false
}

func (x *ScalaPbOptions) GetNoPrimitiveWrappers() bool {
	if x != nil && x.NoPrimitiveWrappers != nil {
		return *x.NoPrimitiveWrappers
	}
	return false
}

func (x *ScalaPbOptions) GetPrimitiveWrappers() bool {
	if x != nil && x.PrimitiveWrappers != nil {
		return *x.PrimitiveWrappers
	}
	return false
}

func (x *ScalaPbOptions) GetCollectionType() string {
	if x != nil && x.CollectionType != nil {
		return *x.CollectionType
	}
	return ""
}

func (x *ScalaPbOptions) GetPreserveUnknownFields() bool {
	if x != nil && x.PreserveUnknownFields != nil {
		return *x.PreserveUnknownFields
	}
	return Default_ScalaPbOptions_PreserveUnknownFields
}

func (x *ScalaPbOptions) GetObjectName() string {
	if x != nil && x.ObjectName != nil {
		return *x.ObjectName
	}
	return ""
}

func (x *ScalaPbOptions) GetScope() ScalaPbOptions_OptionsScope {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ScalaPbOptions_FILE
}

func (x *ScalaPbOptions) GetLenses() bool {
	if x != nil && x.Lenses != nil {
		return *x.Lenses
	}
	return Default_ScalaPbOptions_Lenses
}

func (x *ScalaPbOptions) GetRetainSourceCodeInfo() bool {
	if x != nil && x.RetainSourceCodeInfo != nil {
		return *x.RetainSourceCodeInfo
	}
	return false
}

func (x *ScalaPbOptions) GetMapType() string {
	if x != nil && x.MapType != nil {
		return *x.MapType
	}
	return ""
}

func (x *ScalaPbOptions) GetNoDefaultValuesInConstructor() bool {
	if x != nil && x.NoDefaultValuesInConstructor != nil {
		return *x.NoDefaultValuesInConstructor
	}
	return false
}

func (x *ScalaPbOptions) GetEnumValueNaming() ScalaPbOptions_EnumValueNaming {
	if x != nil && x.EnumValueNaming != nil {
		return *x.EnumValueNaming
	}
	return ScalaPbOptions_AS_IN_PROTO
}

func (x *ScalaPbOptions) GetEnumStripPrefix() bool {
	if x != nil && x.EnumStripPrefix != nil {
		return *x.EnumStripPrefix
	}
	return Default_ScalaPbOptions_EnumStripPrefix
}

func (x *ScalaPbOptions) GetAuxMessageOptions() []*ScalaPbOptions_AuxMessageOptions {
	if x != nil {
		return x.AuxMessageOptions
	}
	return nil
}

func (x *ScalaPbOptions) GetAuxFieldOptions() []*ScalaPbOptions_AuxFieldOptions {
	if x != nil {
		return x.AuxFieldOptions
	}
	return nil
}

func (x *ScalaPbOptions) GetAuxEnumOptions() []*ScalaPbOptions_AuxEnumOptions {
	if x != nil {
		return x.AuxEnumOptions
	}
	return nil
}

func (x *ScalaPbOptions) GetBytesType() string {
	if x != nil && x.BytesType != nil {
		return *x.BytesType
	}
	return ""
}

func (x *ScalaPbOptions) GetTestOnlyNoJavaConversions() bool {
	if x != nil && x.TestOnlyNoJavaConversions != nil {
		return *x.TestOnlyNoJavaConversions
	}
	return false
}

type MessageOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Extends              []string               `protobuf:"bytes,1,rep,name=extends" json:"extends,omitempty"`
	CompanionExtends     []string               `protobuf:"bytes,2,rep,name=companion_extends,json=companionExtends" json:"companion_extends,omitempty"`
	Annotations          []string               `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty"`
	Type                 *string                `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	CompanionAnnotations []string               `protobuf:"bytes,5,rep,name=companion_annotations,json=companionAnnotations" json:"companion_annotations,omitempty"`
	SealedOneofExtends   []string               `protobuf:"bytes,6,rep,name=sealed_oneof_extends,json=sealedOneofExtends" json:"sealed_oneof_extends,omitempty"`
	NoBox                *bool                  `protobuf:"varint,7,opt,name=no_box,json=noBox" json:"no_box,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOptions) GetExtends() []string {
	if x != nil {
		return x.Extends
	}
	return nil
}

func (x *MessageOptions) GetCompanionExtends() []string {
	if x != nil {
		return x.CompanionExtends
	}
	return nil
}

func (x *MessageOptions) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *MessageOptions) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *MessageOptions) GetCompanionAnnotations() []string {
	if x != nil {
		return x.CompanionAnnotations
	}
	return nil
}

func (x *MessageOptions) GetSealedOneofExtends() []string {
	if x != nil {
		return x.SealedOneofExtends
	}
	return nil
}

func (x *MessageOptions) GetNoBox() bool {
	if x != nil && x.NoBox != nil {
		return *x.NoBox
	}
	return false
}

type FieldOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           *string                `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	ScalaName      *string                `protobuf:"bytes,2,opt,name=scala_name,json=scalaName" json:"scala_name,omitempty"`
	CollectionType *string                `protobuf:"bytes,3,opt,name=collection_type,json=collectionType" json:"collection_type,omitempty"`
	KeyType        *string                `protobuf:"bytes,4,opt,name=key_type,json=keyType" json:"key_type,omitempty"`
	ValueType      *string                `protobuf:"bytes,5,opt,name=value_type,json=valueType" json:"value_type,omitempty"`
	Annotations    []string               `protobuf:"bytes,6,rep,name=annotations" json:"annotations,omitempty"`
	MapType        *string                `protobuf:"bytes,7,opt,name=map_type,json=mapType" json:"map_type,omitempty"`
	NoBox          *bool                  `protobuf:"varint,30,opt,name=no_box,json=noBox" json:"no_box,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *FieldOptions) GetScalaName() string {
	if x != nil && x.ScalaName != nil {
		return *x.ScalaName
	}
	return ""
}

func (x *FieldOptions) GetCollectionType() string {
	if x != nil && x.CollectionType != nil {
		return *x.CollectionType
	}
	return ""
}

func (x *FieldOptions) GetKeyType() string {
	if x != nil && x.KeyType != nil {
		return *x.KeyType
	}
	return ""
}

func (x *FieldOptions) GetValueType() string {
	if x != nil && x.ValueType != nil {
		return *x.ValueType
	}
	return ""
}

func (x *FieldOptions) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *FieldOptions) GetMapType() string {
	if x != nil && x.MapType != nil {
		return *x.MapType
	}
	return ""
}

func (x *FieldOptions) GetNoBox() bool {
	if x != nil && x.NoBox != nil {
		return *x.NoBox
	}
	return false
}

type EnumOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Extends          []string               `protobuf:"bytes,1,rep,name=extends" json:"extends,omitempty"`
	CompanionExtends []string               `protobuf:"bytes,2,rep,name=companion_extends,json=companionExtends" json:"companion_extends,omitempty"`
	Type             *string                `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{3}
}

func (x *EnumOptions) GetExtends() []string {
	if x != nil {
		return x.Extends
	}
	return nil
}

func (x *EnumOptions) GetCompanionExtends() []string {
	if x != nil {
		return x.CompanionExtends
	}
	return nil
}

func (x *EnumOptions) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type EnumValueOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extends       []string               `protobuf:"bytes,1,rep,name=extends" json:"extends,omitempty"`
	ScalaName     *string                `protobuf:"bytes,2,opt,name=scala_name,json=scalaName" json:"scala_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{4}
}

func (x *EnumValueOptions) GetExtends() []string {
	if x != nil {
		return x.Extends
	}
	return nil
}

func (x *EnumValueOptions) GetScalaName() string {
	if x != nil && x.ScalaName != nil {
		return *x.ScalaName
	}
	return ""
}

type OneofOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extends       []string               `protobuf:"bytes,1,rep,name=extends" json:"extends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofOptions) Reset() {
	*x = OneofOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOptions) ProtoMessage() {}

func (x *OneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOptions.ProtoReflect.Descriptor instead.
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{5}
}

func (x *OneofOptions) GetExtends() []string {
	if x != nil {
		return x.Extends
	}
	return nil
}

type ScalaPbOptions_AuxMessageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *string                `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Options       *MessageOptions        `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalaPbOptions_AuxMessageOptions) Reset() {
	*x = ScalaPbOptions_AuxMessageOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalaPbOptions_AuxMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalaPbOptions_AuxMessageOptions) ProtoMessage() {}

func (x *ScalaPbOptions_AuxMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalaPbOptions_AuxMessageOptions.ProtoReflect.Descriptor instead.
func (*ScalaPbOptions_AuxMessageOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ScalaPbOptions_AuxMessageOptions) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *ScalaPbOptions_AuxMessageOptions) GetOptions() *MessageOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ScalaPbOptions_AuxFieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *string                `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Options       *FieldOptions          `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalaPbOptions_AuxFieldOptions) Reset() {
	*x = ScalaPbOptions_AuxFieldOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalaPbOptions_AuxFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalaPbOptions_AuxFieldOptions) ProtoMessage() {}

func (x *ScalaPbOptions_AuxFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalaPbOptions_AuxFieldOptions.ProtoReflect.Descriptor instead.
func (*ScalaPbOptions_AuxFieldOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ScalaPbOptions_AuxFieldOptions) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *ScalaPbOptions_AuxFieldOptions) GetOptions() *FieldOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ScalaPbOptions_AuxEnumOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *string                `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Options       *EnumOptions           `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalaPbOptions_AuxEnumOptions) Reset() {
	*x = ScalaPbOptions_AuxEnumOptions{}
	mi := &file_scalapb_scalapb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalaPbOptions_AuxEnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalaPbOptions_AuxEnumOptions) ProtoMessage() {}

func (x *ScalaPbOptions_AuxEnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalapb_scalapb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalaPbOptions_AuxEnumOptions.ProtoReflect.Descriptor instead.
func (*ScalaPbOptions_AuxEnumOptions) Descriptor() ([]byte, []int) {
	return file_scalapb_scalapb_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ScalaPbOptions_AuxEnumOptions) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *ScalaPbOptions_AuxEnumOptions) GetOptions() *EnumOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

var file_scalapb_scalapb_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*ScalaPbOptions)(nil),
		Field:         1020,
		Name:          "scalapb.options",
		Tag:           "bytes,1020,opt,name=options",
		Filename:      "scalapb/scalapb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         1020,
		Name:          "scalapb.message",
		Tag:           "bytes,1020,opt,name=message",
		Filename:      "scalapb/scalapb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         1020,
		Name:          "scalapb.field",
		Tag:           "bytes,1020,opt,name=field",
		Filename:      "scalapb/scalapb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         1020,
		Name:          "scalapb.enum_options",
		Tag:           "bytes,1020,opt,name=enum_options",
		Filename:      "scalapb/scalapb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         1020,
		Name:          "scalapb.enum_value",
		Tag:           "bytes,1020,opt,name=enum_value",
		Filename:      "scalapb/scalapb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofOptions)(nil),
		Field:         1020,
		Name:          "scalapb.oneof",
		Tag:           "bytes,1020,opt,name=oneof",
		Filename:      "scalapb/scalapb.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional scalapb.ScalaPbOptions options = 1020;
	E_Options = &file_scalapb_scalapb_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional scalapb.MessageOptions message = 1020;
	E_Message = &file_scalapb_scalapb_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional scalapb.FieldOptions field = 1020;
	E_Field = &file_scalapb_scalapb_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional scalapb.EnumOptions enum_options = 1020;
	E_EnumOptions = &file_scalapb_scalapb_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional scalapb.EnumValueOptions enum_value = 1020;
	E_EnumValue = &file_scalapb_scalapb_proto_extTypes[4]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional scalapb.OneofOptions oneof = 1020;
	E_Oneof = &file_scalapb_scalapb_proto_extTypes[5]
)

var File_scalapb_scalapb_proto protoreflect.FileDescriptor

const file_scalapb_scalapb_proto_rawDesc = "" +
	"\n" +
	"\x15scalapb/scalapb.proto\x12\ascalapb\x1a google/protobuf/descriptor.proto\"\xe8\v\n" +
	"\x0eScalaPbOptions\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12!\n" +
	"\fflat_package\x18\x02 \x01(\bR\vflatPackage\x12\x16\n" +
	"\x06import\x18\x03 \x03(\tR\x06import\x12\x1a\n" +
	"\bpreamble\x18\x04 \x03(\tR\bpreamble\x12\x1f\n" +
	"\vsingle_file\x18\x05 \x01(\bR\n" +
	"singleFile\x122\n" +
	"\x15no_primitive_wrappers\x18\a \x01(\bR\x13noPrimitiveWrappers\x12-\n" +
	"\x12primitive_wrappers\x18\x06 \x01(\bR\x11primitiveWrappers\x12'\n" +
	"\x0fcollection_type\x18\b \x01(\tR\x0ecollectionType\x12<\n" +
	"\x17preserve_unknown_fields\x18\t \x01(\b:\x04trueR\x15preserveUnknownFields\x12\x1f\n" +
	"\vobject_name\x18\n" +
	" \x01(\tR\n" +
	"objectName\x12:\n" +
	"\x05scope\x18\v \x01(\x0e2$.scalapb.ScalaPbOptions.OptionsScopeR\x05scope\x12\x1c\n" +
	"\x06lenses\x18\f \x01(\b:\x04trueR\x06lenses\x125\n" +
	"\x17retain_source_code_info\x18\r \x01(\bR\x14retainSourceCodeInfo\x12\x19\n" +
	"\bmap_type\x18\x0e \x01(\tR\amapType\x12F\n" +
	" no_default_values_in_constructor\x18\x0f \x01(\bR\x1cnoDefaultValuesInConstructor\x12S\n" +
	"\x11enum_value_naming\x18\x10 \x01(\x0e2'.scalapb.ScalaPbOptions.EnumValueNamingR\x0fenumValueNaming\x121\n" +
	"\x11enum_strip_prefix\x18\x11 \x01(\b:\x05falseR\x0fenumStripPrefix\x12Y\n" +
	"\x13aux_message_options\x18\x12 \x03(\v2).scalapb.ScalaPbOptions.AuxMessageOptionsR\x11auxMessageOptions\x12S\n" +
	"\x11aux_field_options\x18\x13 \x03(\v2'.scalapb.ScalaPbOptions.AuxFieldOptionsR\x0fauxFieldOptions\x12P\n" +
	"\x10aux_enum_options\x18\x14 \x03(\v2&.scalapb.ScalaPbOptions.AuxEnumOptionsR\x0eauxEnumOptions\x12\x1d\n" +
	"\n" +
	"bytes_type\x18\x15 \x01(\tR\tbytesType\x12B\n" +
	"\x1dtest_only_no_java_conversions\x18\xa1\x8d\x06 \x01(\bR\x19testOnlyNoJavaConversions\x1a^\n" +
	"\x11AuxMessageOptions\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.scalapb.MessageOptionsR\aoptions\x1aZ\n" +
	"\x0fAuxFieldOptions\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12/\n" +
	"\aoptions\x18\x02 \x01(\v2\x15.scalapb.FieldOptionsR\aoptions\x1aX\n" +
	"\x0eAuxEnumOptions\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12.\n" +
	"\aoptions\x18\x02 \x01(\v2\x14.scalapb.EnumOptionsR\aoptions\"%\n" +
	"\fOptionsScope\x12\b\n" +
	"\x04FILE\x10\x00\x12\v\n" +
	"\aPACKAGE\x10\x01\"2\n" +
	"\x0fEnumValueNaming\x12\x0f\n" +
	"\vAS_IN_PROTO\x10\x00\x12\x0e\n" +
	"\n" +
	"CAMEL_CASE\x10\x01\"\x8b\x02\n" +
	"\x0eMessageOptions\x12\x18\n" +
	"\aextends\x18\x01 \x03(\tR\aextends\x12+\n" +
	"\x11companion_extends\x18\x02 \x03(\tR\x10companionExtends\x12 \n" +
	"\vannotations\x18\x03 \x03(\tR\vannotations\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x123\n" +
	"\x15companion_annotations\x18\x05 \x03(\tR\x14companionAnnotations\x120\n" +
	"\x14sealed_oneof_extends\x18\x06 \x03(\tR\x12sealedOneofExtends\x12\x15\n" +
	"\x06no_box\x18\a \x01(\bR\x05noBox\"\xf8\x01\n" +
	"\fFieldOptions\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"scala_name\x18\x02 \x01(\tR\tscalaName\x12'\n" +
	"\x0fcollection_type\x18\x03 \x01(\tR\x0ecollectionType\x12\x19\n" +
	"\bkey_type\x18\x04 \x01(\tR\akeyType\x12\x1d\n" +
	"\n" +
	"value_type\x18\x05 \x01(\tR\tvalueType\x12 \n" +
	"\vannotations\x18\x06 \x03(\tR\vannotations\x12\x19\n" +
	"\bmap_type\x18\a \x01(\tR\amapType\x12\x15\n" +
	"\x06no_box\x18\x1e \x01(\bR\x05noBox\"h\n" +
	"\vEnumOptions\x12\x18\n" +
	"\aextends\x18\x01 \x03(\tR\aextends\x12+\n" +
	"\x11companion_extends\x18\x02 \x03(\tR\x10companionExtends\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"K\n" +
	"\x10EnumValueOptions\x12\x18\n" +
	"\aextends\x18\x01 \x03(\tR\aextends\x12\x1d\n" +
	"\n" +
	"scala_name\x18\x02 \x01(\tR\tscalaName\"(\n" +
	"\fOneofOptions\x12\x18\n" +
	"\aextends\x18\x01 \x03(\tR\aextends:P\n" +
	"\aoptions\x12\x1c.google.protobuf.FileOptions\x18\xfc\a \x01(\v2\x17.scalapb.ScalaPbOptionsR\aoptions:S\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xfc\a \x01(\v2\x17.scalapb.MessageOptionsR\amessage:K\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xfc\a \x01(\v2\x15.scalapb.FieldOptionsR\x05field:V\n" +
	"\fenum_options\x12\x1c.google.protobuf.EnumOptions\x18\xfc\a \x01(\v2\x14.scalapb.EnumOptionsR\venumOptions:\\\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18\xfc\a \x01(\v2\x19.scalapb.EnumValueOptionsR\tenumValue:K\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\xfc\a \x01(\v2\x15.scalapb.OneofOptionsR\x05oneofBX\xe2?\x13\n" +
	"\x0fscalapb.options\x10\x01\n" +
	"\x0fscalapb.optionsZ/github.com/stackb/scala-gazelle/scalapb;scalapb"

var (
	file_scalapb_scalapb_proto_rawDescOnce sync.Once
	file_scalapb_scalapb_proto_rawDescData []byte
)

func file_scalapb_scalapb_proto_rawDescGZIP() []byte {
	file_scalapb_scalapb_proto_rawDescOnce.Do(func() {
		file_scalapb_scalapb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalapb_scalapb_proto_rawDesc), len(file_scalapb_scalapb_proto_rawDesc)))
	})
	return file_scalapb_scalapb_proto_rawDescData
}

var file_scalapb_scalapb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scalapb_scalapb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_scalapb_scalapb_proto_goTypes = []any{
	(ScalaPbOptions_OptionsScope)(0),         // 0: scalapb.ScalaPbOptions.OptionsScope
	(ScalaPbOptions_EnumValueNaming)(0),      // 1: scalapb.ScalaPbOptions.EnumValueNaming
	(*ScalaPbOptions)(nil),                   // 2: scalapb.ScalaPbOptions
	(*MessageOptions)(nil),                   // 3: scalapb.MessageOptions
	(*FieldOptions)(nil),                     // 4: scalapb.FieldOptions
	(*EnumOptions)(nil),                      // 5: scalapb.EnumOptions
	(*EnumValueOptions)(nil),                 // 6: scalapb.EnumValueOptions
	(*OneofOptions)(nil),                     // 7: scalapb.OneofOptions
	(*ScalaPbOptions_AuxMessageOptions)(nil), // 8: scalapb.ScalaPbOptions.AuxMessageOptions
	(*ScalaPbOptions_AuxFieldOptions)(nil),   // 9: scalapb.ScalaPbOptions.AuxFieldOptions
	(*ScalaPbOptions_AuxEnumOptions)(nil),    // 10: scalapb.ScalaPbOptions.AuxEnumOptions
	(*descriptorpb.FileOptions)(nil),         // 11: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),      // 12: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),        // 13: google.protobuf.FieldOptions
	(*descriptorpb.EnumOptions)(nil),         // 14: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil),    // 15: google.protobuf.EnumValueOptions
	(*descriptorpb.OneofOptions)(nil),        // 16: google.protobuf.OneofOptions
}
var file_scalapb_scalapb_proto_depIdxs = []int32{
	0,  // 0: scalapb.ScalaPbOptions.scope:type_name -> scalapb.ScalaPbOptions.OptionsScope
	1,  // 1: scalapb.ScalaPbOptions.enum_value_naming:type_name -> scalapb.ScalaPbOptions.EnumValueNaming
	8,  // 2: scalapb.ScalaPbOptions.aux_message_options:type_name -> scalapb.ScalaPbOptions.AuxMessageOptions
	9,  // 3: scalapb.ScalaPbOptions.aux_field_options:type_name -> scalapb.ScalaPbOptions.AuxFieldOptions
	10, // 4: scalapb.ScalaPbOptions.aux_enum_options:type_name -> scalapb.ScalaPbOptions.AuxEnumOptions
	3,  // 5: scalapb.ScalaPbOptions.AuxMessageOptions.options:type_name -> scalapb.MessageOptions
	4,  // 6: scalapb.ScalaPbOptions.AuxFieldOptions.options:type_name -> scalapb.FieldOptions
	5,  // 7: scalapb.ScalaPbOptions.AuxEnumOptions.options:type_name -> scalapb.EnumOptions
	11, // 8: scalapb.options:extendee -> google.protobuf.FileOptions
	12, // 9: scalapb.message:extendee -> google.protobuf.MessageOptions
	13, // 10: scalapb.field:extendee -> google.protobuf.FieldOptions
	14, // 11: scalapb.enum_options:extendee -> google.protobuf.EnumOptions
	15, // 12: scalapb.enum_value:extendee -> google.protobuf.EnumValueOptions
	16, // 13: scalapb.oneof:extendee -> google.protobuf.OneofOptions
	2,  // 14: scalapb.options:type_name -> scalapb.ScalaPbOptions
	3,  // 15: scalapb.message:type_name -> scalapb.MessageOptions
	4,  // 16: scalapb.field:type_name -> scalapb.FieldOptions
	5,  // 17: scalapb.enum_options:type_name -> scalapb.EnumOptions
	6,  // 18: scalapb.enum_value:type_name -> scalapb.EnumValueOptions
	7,  // 19: scalapb.oneof:type_name -> scalapb.OneofOptions
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	14, // [14:20] is the sub-list for extension type_name
	8,  // [8:14] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_scalapb_scalapb_proto_init() }
func file_scalapb_scalapb_proto_init() {
	if File_scalapb_scalapb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalapb_scalapb_proto_rawDesc), len(file_scalapb_scalapb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_scalapb_scalapb_proto_goTypes,
		DependencyIndexes: file_scalapb_scalapb_proto_depIdxs,
		EnumInfos:         file_scalapb_scalapb_proto_enumTypes,
		MessageInfos:      file_scalapb_scalapb_proto_msgTypes,
		ExtensionInfos:    file_scalapb_scalapb_proto_extTypes,
	}.Build()
	File_scalapb_scalapb_proto = out.File
	file_scalapb_scalapb_proto_goTypes = nil
	file_scalapb_scalapb_proto_depIdxs = nil
}
